// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin-dashboard" | "/boutique" | "/boutique/[shopId]" | "/boutiques" | "/cart" | "/client-dashboard" | "/commandes-recues" | "/commandes/[orderId]" | "/complete-profile" | "/contact" | "/dashboard/messages" | "/livraisons" | "/login" | "/merchant-dashboard" | "/messages/[userId]" | "/notifications" | "/profile" | "/redirect" | "/register" | "/stories" | "/supplier-dashboard" | "/support" | "/verification-pending" | "/verify-code" | "/verify-phone" | "/whatsapp" | "/whatsapp-links"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin-dashboard" | "/boutique/[shopId]" | "/cart" | "/client-dashboard" | "/merchant-dashboard" | "/profile" | "/supplier-dashboard" | "/whatsapp"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin-dashboard": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/boutique": {}
  "/boutique/[shopId]": { "shopId": string; }
  "/boutiques": {}
  "/cart": {}
  "/client-dashboard": {}
  "/commandes-recues": {}
  "/commandes/[orderId]": { "orderId": string; }
  "/complete-profile": {}
  "/contact": {}
  "/dashboard/messages": {}
  "/livraisons": {}
  "/login": {}
  "/merchant-dashboard": {}
  "/messages/[userId]": { "userId": string; }
  "/notifications": {}
  "/profile": {}
  "/redirect": {}
  "/register": {}
  "/stories": {}
  "/supplier-dashboard": {}
  "/support": {}
  "/verification-pending": {}
  "/verify-code": {}
  "/verify-phone": {}
  "/whatsapp": {}
  "/whatsapp-links": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin-dashboard": never
  "/boutique/[shopId]": never
  "/cart": never
  "/client-dashboard": never
  "/merchant-dashboard": never
  "/profile": never
  "/supplier-dashboard": never
  "/whatsapp": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
