// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-dashboard">> = Specific
  const handler = {} as typeof import("../../app/admin-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/boutique/[shopId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/boutique/[shopId]">> = Specific
  const handler = {} as typeof import("../../app/boutique/[shopId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/boutique/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/boutique">> = Specific
  const handler = {} as typeof import("../../app/boutique/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/boutiques/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/boutiques">> = Specific
  const handler = {} as typeof import("../../app/boutiques/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../app/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/client-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client-dashboard">> = Specific
  const handler = {} as typeof import("../../app/client-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/commandes-recues/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/commandes-recues">> = Specific
  const handler = {} as typeof import("../../app/commandes-recues/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/commandes/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/commandes/[orderId]">> = Specific
  const handler = {} as typeof import("../../app/commandes/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/complete-profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/complete-profile">> = Specific
  const handler = {} as typeof import("../../app/complete-profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/messages">> = Specific
  const handler = {} as typeof import("../../app/dashboard/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/livraisons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/livraisons">> = Specific
  const handler = {} as typeof import("../../app/livraisons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/merchant-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/merchant-dashboard">> = Specific
  const handler = {} as typeof import("../../app/merchant-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/messages/[userId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messages/[userId]">> = Specific
  const handler = {} as typeof import("../../app/messages/[userId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/redirect/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/redirect">> = Specific
  const handler = {} as typeof import("../../app/redirect/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/stories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stories">> = Specific
  const handler = {} as typeof import("../../app/stories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/supplier-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supplier-dashboard">> = Specific
  const handler = {} as typeof import("../../app/supplier-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verification-pending/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verification-pending">> = Specific
  const handler = {} as typeof import("../../app/verification-pending/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verify-code/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-code">> = Specific
  const handler = {} as typeof import("../../app/verify-code/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verify-phone/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-phone">> = Specific
  const handler = {} as typeof import("../../app/verify-phone/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/whatsapp-links/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/whatsapp-links">> = Specific
  const handler = {} as typeof import("../../app/whatsapp-links/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/whatsapp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/whatsapp">> = Specific
  const handler = {} as typeof import("../../app/whatsapp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/admin-dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin-dashboard">> = Specific
  const handler = {} as typeof import("../../app/admin-dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/boutique/[shopId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/boutique/[shopId]">> = Specific
  const handler = {} as typeof import("../../app/boutique/[shopId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cart/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../app/cart/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/client-dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/client-dashboard">> = Specific
  const handler = {} as typeof import("../../app/client-dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/merchant-dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/merchant-dashboard">> = Specific
  const handler = {} as typeof import("../../app/merchant-dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/supplier-dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/supplier-dashboard">> = Specific
  const handler = {} as typeof import("../../app/supplier-dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/whatsapp/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/whatsapp">> = Specific
  const handler = {} as typeof import("../../app/whatsapp/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
