var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/support/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__175qaf3._.js")
R.c("server/chunks/ssr/node_modules_09r9c10._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1w-sf8x.js")
R.c("server/chunks/ssr/[root-of-the-server]__14ijnbv._.js")
R.c("server/chunks/ssr/node_modules_next_dist_172hvm-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0juf3t_._.js")
R.c("server/chunks/ssr/app_error_tsx_1zds1ns._.js")
R.c("server/chunks/ssr/app_loading_tsx_0a1flg9._.js")
R.c("server/chunks/ssr/app_not-found_tsx_1ez0193._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_support_page_actions_09c07d6.js")
R.m(8215)
module.exports=R.m(8215).exports
