name: CI pour les pull request dans master

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-22.04

    environment: prod

    env:
      APP_NAME: waxci-web-frontend-prod
      NODE_ENV: production

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image localement
        run: |
          docker build --target prod -t ${{ env.APP_NAME }}:test .

      - name: Run container for healthcheck
        run: |
          docker run -d --name temp-app -p 3000:3000 ${{ env.APP_NAME }}:test

          ready=false
          for i in {1..20}; do
            if curl -fsS http://localhost:3000/ > /dev/null; then
              echo "Application prête"
              ready=true
              break
            fi
            sleep 3
          done

          docker logs temp-app

          if [ "$ready" != "true" ]; then
            docker stop temp-app
            docker rm temp-app
            exit 1
          fi

          docker stop temp-app
          docker rm temp-app

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          target: prod
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/${{ vars.APP_NAME }}:latest
            ${{ vars.DOCKER_USERNAME }}/${{ vars.APP_NAME }}:${{ github.sha }}
            ${{ vars.DOCKER_USERNAME }}/${{ vars.APP_NAME }}:${{ github.ref_name }}
